"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
final_space = true
version = 2

[palette]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

  [[blocks.segments]]
  type = "path"
  style = "plain"
  foreground = "p:overlay1"
  template = "{{ .Path }}"

    [blocks.segments.properties]
    folder_icon = ".."
    home_icon = "~"
    style = "mixed"
    mixed_threshold = 12

[[blocks]]
type = "prompt"
alignment = "right"

  [[blocks.segments]]
  type = "upgrade"
  style = "plain"
  template = "<p:green,transparent></><p:surface0,p:green> </><p:text,p:surface0> {{ .Current }}</><p:surface0,transparent></> "

  [[blocks.segments]]
  type = "status"
  style = "plain"
  template = "<p:red,transparent></><p:surface0,p:red> </><p:text,p:surface0> {{ .Code }}</><p:surface0,transparent></> "

    [blocks.segments.properties]
    always_enabled = false

  [[blocks.segments]]
  type = "git"
  style = "plain"
  foreground = "p:green"
  background = "p:green"
  background_templates = [
    "{{ if or (.Working.Changed) (.Staging.Changed) }}p:yellow{{ end }}",
    "{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:peach{{ end }}",
    "{{ if gt .Ahead 0 }}p:mauve{{ end }}",
    "{{ if gt .Behind 0 }}p:mauve{{ end }}"
  ]
  foreground_templates = [
    "{{ if or (.Working.Changed) (.Staging.Changed) }}p:yellow{{ end }}",
    "{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:peach{{ end }}",
    "{{ if gt .Ahead 0 }}p:mauve{{ end }}",
    "{{ if gt .Behind 0 }}p:mauve{{ end }}"
  ]
  template = "<,transparent></><p:surface0>{{ .UpstreamIcon }}</><p:text,p:surface0> {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}</><p:surface0,transparent></><,transparent> </>"

    [blocks.segments.properties]
    fetch_status = true
    fetch_upstream_icon = true
    fetch_bare_info = true

  [[blocks.segments]]
  type = "executiontime"
  style = "plain"
  template = "<p:teal,transparent></><p:surface0,p:teal> </><p:text,p:surface0> {{ .FormattedMs }}</><p:surface0,transparent></>"

    [blocks.segments.properties]
    style = "austin"
    always_enabled = true
    threshold = 100

  [[blocks.segments]]
  type = "time"
  style = "plain"
  template = " <p:blue,transparent></><p:surface0,p:blue> </><p:text,p:surface0> {{ .CurrentDate | date .Format }}</><p:surface0,transparent></>"

    [blocks.segments.properties]
    time_format = "15:04"

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

  [[blocks.segments]]
  type = "session"
  style = "plain"
  template = "{{ if .Root }}<p:red>{{ else }}<p:lavender>{{ end }}{{ .UserName }}</>{{ if .SSHSession }}<p:text>@</><p:mauve>{{ .HostName }}</>{{ end }} "
  

  [[blocks.segments]]
  type = "status"
  style = "plain"
  foreground = "p:green"
  foreground_templates = [ "{{ if gt .Code 0 }}p:red{{ end }}" ]
  template = ""

    [blocks.segments.properties]
    always_enabled = true

