"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version = 3
final_space = true

[palette]
  base = '#24273a'
  blue = '#8aadf4'
  crust = '#181926'
  flamingo = '#f0c6c6'
  green = '#a6da95'
  lavender = '#b7bdf8'
  mantle = '#1e2030'
  maroon = '#ee99a0'
  mauve = '#c6a0f6'
  overlay0 = '#6e738d'
  overlay1 = '#8087a2'
  overlay2 = '#939ab7'
  peach = '#f5a97f'
  pink = '#f5bde6'
  red = '#ed8796'
  rosewater = '#f4dbd6'
  sapphire = '#7dc4e4'
  sky = '#91d7e3'
  subtext0 = '#a5adcb'
  subtext1 = '#b8c0e0'
  surface0 = '#363a4f'
  surface1 = '#494d64'
  surface2 = '#5b6078'
  teal = '#8bd5ca'
  text = '#cad3f5'
  yellow = '#eed49f'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '{{ .Path }}'
    foreground = 'p:overlay1'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      folder_icon = '..'
      home_icon = '~'
      mixed_threshold = 12
      style = 'mixed'

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    template = '<p:green,transparent></><p:surface0,p:green> </><p:text,p:surface0> {{ .Current }}</><p:surface0,transparent></> '
    type = 'upgrade'
    style = 'plain'

#    [blocks.segments.properties]
#      cache_duration = 'none'

  [[blocks.segments]]
    template = '<p:red,transparent></><p:surface0,p:red> </><p:text,p:surface0> {{ .Code }}</><p:surface0,transparent></> '
    type = 'status'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = '72h'

 [[blocks.segments]]
    template = '<,transparent></><p:surface0>{{if .UpstreamIcon }}{{.UpstreamIcon}}{{else}} {{end}}</><p:text,p:surface0> {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}</><p:surface0,transparent></><,transparent> </>'
    foreground = 'p:green'
    background = 'p:green'
    type = 'git'
    style = 'plain'
    foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:yellow{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:peach{{ end }}', '{{ if gt .Ahead 0 }}p:mauve{{ end }}', '{{ if gt .Behind 0 }}p:mauve{{ end }}']
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:yellow{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:peach{{ end }}', '{{ if gt .Ahead 0 }}p:mauve{{ end }}', '{{ if gt .Behind 0 }}p:mauve{{ end }}']

    [blocks.segments.properties]
      cache_duration = 'none'
      fetch_bare_info = true
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    template = '<p:teal,transparent></><p:surface0,p:teal> </><p:text,p:surface0> {{ .FormattedMs }}</><p:surface0,transparent></>'
    type = 'executiontime'
    style = 'plain'

    [blocks.segments.properties]
      always_enabled = true
      cache_duration = 'none'
      style = 'austin'
      threshold = 100

  [[blocks.segments]]
    template = ' <p:blue,transparent></><p:surface0,p:blue> </><p:text,p:surface0> {{ .CurrentDate | date .Format }}</><p:surface0,transparent></>'
    type = 'time'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      time_format = '15:04'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '{{ if .Root }}<p:red>{{ else }}<p:lavender>{{ end }}{{ .UserName }}</><p:text>@</><p:mauve>{{ .HostName }}</> '
    type = 'session'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ''
    foreground = 'p:green'
    type = 'status'
    style = 'plain'
    foreground_templates = ['{{ if gt .Code 0 }}p:red{{ end }}']

    [blocks.segments.properties]
      always_enabled = true
      cache_duration = 'none'
